version: '2'
services:
  factorio:
    container_name: factorio
    build: .
    restart: always
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - factorio:/factorio

volumes:
  factorio:
